version: "2.4"

services:
  db:
    image: postgres:15-alpine
    container_name: "postgres_db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pg_db
      POSTGRES_PORT: 5433
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    restart: always

  redis:
    image: redis:7-alpine
    container_name: "redis_cache"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - data_pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"

volumes:
  postgres_data:
  data_pgadmin:
  redis_data:
